### ISSUE TITLE
CUDA runtime error

### ISSUE THREAD

**Issue by yashsingla984** [swz30/MPRNet#105]
I want to use deblurred  pretrained model to check the results. So I have run the command as mentioned in quick Run. But I got the CUDA runtime error 
Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    restored = model(input_)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "Deblurring\MPRNet.py", line 313, in forward
    x2top  = self.shallow_feat2(x2top_img)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "Deblurring\MPRNet.py", line 54, in forward
    res = self.body(x)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\modules\activation.py", line 961, in forward
    return F.prelu(input, self.weight)
  File "C:\Users\Yash Singla\.conda\envs\pytorch1\lib\site-packages\torch\nn\functional.py", line 1121, in prelu
    return torch.prelu(input, weight)
RuntimeError: CUDA out of memory. Tried to allocate 168.00 MiB (GPU 0; 4.00 GiB total capacity; 2.56 GiB already allocated; 83.45 MiB free; 403.98 MiB cached)

I don't know how to solve this issue. As I think if the model is pretrained then why we are using CUDA we just be having simple matrix multiplication and getting output. Please help

**Comment by yashsingla984** [comment]
This issue can be solved if you give input image of size 256 *256 . I have olve this issue by using resizing image using this link https://www.reduceimages.com/   I hope then issue can be resolved
