### ISSUE TITLE
meet Runtime error when training deblur codes

### ISSUE THREAD

**Issue by hm-better** [swz30/MPRNet#112]
Traceback (most recent call last):
  File "/data/h00026370/Moon/codes/MPRNet/Deblurring/train.py", line 120, in <module>
    loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
  File "<__array_function__ internals>", line 6, in sum
  File "/home/leipeng/anaconda3/envs/mprnet/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2260, in sum
    initial=initial, where=where)
  File "/home/leipeng/anaconda3/envs/mprnet/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/leipeng/anaconda3/envs/mprnet/lib/python3.7/site-packages/torch/tensor.py", line 458, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

**Comment by linqwn** [comment]
I hope the author can answer this question，thanks.

**Comment by swz30** [comment]
Please check this https://github.com/swz30/MPRNet/issues/101#issuecomment-1089913560

**Comment by linqwn** [comment]
According to what you said, the following problem appears again
![image](https://user-images.githubusercontent.com/93809251/167252631-38242725-8d4a-454f-9097-047294454fe4.png)

**Comment by swz30** [comment]
See this https://github.com/swz30/MPRNet/issues/108#issuecomment-1078691640
