### ISSUE TITLE
About Training, how to deal with this problem?

### ISSUE THREAD

**Issue by jjjjzyyyyyy** [swz30/MPRNet#123]
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    for ii, data_val in enumerate((val_loader), 0):
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mail/2019p9/p930026055/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/mail/2019p9/p930026055/directory_2/MPRNet/Deraining/dataset_RGB.py", line 111, in __getitem__
    inp_path = self.inp_filenames[index_]
IndexError: list index out of range

**Comment by ELan-real** [comment]
Hi, have you solved this problem? Could you tell the solution?

**Comment by jjjjzyyyyyy** [comment]
Hi, you can check your directory of dataset or whether each item of dataset has proper name.



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 21, 2022 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [swz30/MPRNet] About Training, how to deal with this problem?(Issue #123)




 
Hi, have you solved this problem? Could you tell the solution?

**Comment by Feecuin** [comment]
> 您好，您可以检查您的数据集目录或数据集的每个项目是否有正确的名称。
> [……](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Nov 21, 2022 18:10 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [swz30/MPRNet] About Training, how to deal with this problem?(Issue #123) Hi, have you solved this problem? Could you tell the solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，请问下可以看看你的数据集是如何存放的吗？我发现我训练的时候save_images：true 还是不能出图，PSNR一直都上不去
