### ISSUE TITLE
some issue about the data loader~

### ISSUE THREAD

**Issue by leefly072** [swz30/MPRNet#16]
Thank you very much for sharing, this is a very interesting paper. I face some issues when I try to train the denoise and Derain model. when I run the Derain the train.py and download the dataset.i face the 
"RuntimeError: stack expects each tensor to be equal size, but got [3, 229, 256] at entry 0 and [3, 256, 171] at entry 1".  should I to pretrain the data in the same size before I run the train.py of the Derain the model?  could you give me a hand for this problem? thanks very much

**Comment by adityac8** [comment]
Hi
Are you trying to run our deraining model? If that is the case, could you please tell if you are training it on the provided dataset or some other dataset. Also, are you using the provided dataloader for it?

Thanks

**Comment by leefly072** [comment]
Thank you very much for your reply.  I found the dataset issues is caused by the unpaired, and I already fix it . but the following problem is confused me.
Traceback (most recent call last):
  File "/data/lifei/MPRNet-main/Deraining/train.py", line 120, in <module>
    loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))]).cpu()
  File "<__array_function__ internals>", line 5, in sum
  File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2247, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/lifei/.local/lib/python3.8/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by adityac8** [comment]
The loss should look something like
https://github.com/swz30/MPRNet/blob/bfe0b888df35bfc775362647265661832bd9f683/Deraining/train.py#L120-L121

Remove `.cpu()` from it and it should work.

Thanks

**Comment by leefly072** [comment]
the same issue when I run the train.py.
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
===> Start Epoch 1 End Epoch 251
===> Loading datasets
  0%|                                                   | 0/857 [00:00<?, ?it/s]/home/lifei/.local/lib/python3.8/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
  0%|                                                   | 0/857 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "/data/lifei/MPRNet-main/Deraining/train.py", line 120, in <module>
    loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
  File "<__array_function__ internals>", line 5, in sum
  File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2247, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/lifei/.local/lib/python3.8/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
I add the cpu() to solve the error. and found it is not use for train.py to add cpu()。

**Comment by adityac8** [comment]
Hi

You seem to have a different version of pytorch installed. Make sure that you use `pytorch==1.1` for our codes. After going to that version, please tell if the error is still there.

Thanks

**Comment by leefly072** [comment]
You review is very very useful for me, and help me to learning the code quickly.  but when i run the model after 4epoch,some issue is coming.
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    psnr_val_rgb  = torch.stack(psnr_val_rgb).mean().item()
RuntimeError: expected a non-empty list of Tensors

**Comment by adityac8** [comment]
You have to make sure that you give the correct directory for the validation data.

**Comment by leefly072** [comment]
Thank you for your reply and help. I wish you all the best.

**Comment by adityac8** [comment]
Thank you.

**Comment by GuoliangShi** [comment]
> the same issue when I run the train.py.
> UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`. Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
> warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
> ===> Start Epoch 1 End Epoch 251
> ===> Loading datasets
> 0%| | 0/857 [00:00<?, ?it/s]/home/lifei/.local/lib/python3.8/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
> warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
> 0%| | 0/857 [00:27<?, ?it/s]
> Traceback (most recent call last):
> File "/data/lifei/MPRNet-main/Deraining/train.py", line 120, in
> loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
> File "<**array_function** internals>", line 5, in sum
> File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2247, in sum
> return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
> File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
> return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> File "/home/lifei/.local/lib/python3.8/site-packages/torch/tensor.py", line 630, in **array**
> return self.numpy()
> TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
> I add the cpu() to solve the error. and found it is not use for train.py to add cpu()。



> the same issue when I run the train.py.
> UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`. Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
> warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
> ===> Start Epoch 1 End Epoch 251
> ===> Loading datasets
> 0%| | 0/857 [00:00<?, ?it/s]/home/lifei/.local/lib/python3.8/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
> warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
> 0%| | 0/857 [00:27<?, ?it/s]
> Traceback (most recent call last):
> File "/data/lifei/MPRNet-main/Deraining/train.py", line 120, in
> loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
> File "<**array_function** internals>", line 5, in sum
> File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2247, in sum
> return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
> File "/home/lifei/.conda/envs/TTSR/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
> return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> File "/home/lifei/.local/lib/python3.8/site-packages/torch/tensor.py", line 630, in **array**
> return self.numpy()
> TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
> I add the cpu() to solve the error. and found it is not use for train.py to add cpu()。

Hi, I have the same error with pytorch 1.8.1. when I train at pytorch 1.1, get difference error:
===> Start Epoch 1 End Epoch 3001
===> Loading datasets
  0%|                                                                                                   | 0/5520 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
  File "<__array_function__ internals>", line 6, in sum
  File "/home/bxx/anaconda3/envs/pytorch1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2248, in sum
    initial=initial, where=where)
  File "/home/bxx/anaconda3/envs/pytorch1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/bxx/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/tensor.py", line 458, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

How did you solve it?

**Comment by ffleader1** [comment]
> pytorch==1.1

Hello
so how dod you solve this problem?

**Comment by yanghan0617** [comment]
> Thank you very much for sharing, this is a very interesting paper. I face some issues when I try to train the denoise and Derain model. when I run the Derain the train.py and download the dataset.i face the "RuntimeError: stack expects each tensor to be equal size, but got [3, 229, 256] at entry 0 and [3, 256, 171] at entry 1". should I to pretrain the data in the same size before I run the train.py of the Derain the model? could you give me a hand for this problem? thanks very much

请问你是如何解决这个问题的，我检查了数据集没有问题
