### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by adamsatyr** [swz30/MPRNet#36]
Edit: I found the issue: CUDA 9.0. It doesn't support NVidia 2xxxx series (Turing). Can you change that to something that would work with newer GPU cards?

EDIT2: Found a solution: use` conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch`

Hello,
I'm trying to run this and I did everything as in instruction, but I get this error (RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED) when I try to run pretrained model (which I downloaded).
I'm using in on Windows.

What could be a problem here?

python demo.py --task Denoising --input_dir ./export --result_dir ./output/

Full traceback
```
Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    restored = model(input_)
  File "D:\Users\user_name\miniconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "Denoising\MPRNet.py", line 284, in forward
    x1ltop = self.shallow_feat1(x1ltop_img)
  File "D:\Users\user_name\miniconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Users\user_name\miniconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Users\user_name\miniconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Users\user_name\miniconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by swz30** [comment]
Hi @adamsatyr 

Thank you for providing EDIT2 as a solution (cudatoolkit=10.0) for those who are using NVIDIA 2xxx series.
