### ISSUE TITLE
hi，我在运行代码时，出现一个问题

### ISSUE THREAD

**Issue by zhaoguoqing12** [swz30/MPRNet#59]
我并没有按照要求使用 conda install pytorch=1.1 torchvision=0.3 cudatoolkit=9.0 -c pytorch 安装pytroch,
我使用 conda install pytorch=1.1 torchvision=0.3 cudatoolkit=10.0 -c pytorch 进行安装。但是出现了一个错误

Traceback (most recent call last):
  File "train.py", line 120, in <module>
    loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
  File "<__array_function__ internals>", line 6, in sum
  File "/local_data/li/anaconda3/envs/MPRNet/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2248, in sum
    initial=initial, where=where)
  File "/local_data/li/anaconda3/envs/MPRNet/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/local_data/li/anaconda3/envs/MPRNet/lib/python3.7/site-packages/torch/tensor.py", line 458, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

是否是torch的原因，如果是，使用现有的torch怎样解决呢？

**Comment by adityac8** [comment]
Hi @zhaoguoqing12 

You can refer to https://github.com/swz30/MPRNet/issues/45#issuecomment-837000839

Thanks
